In [1]:
print("Hi")

Hi


In [2]:
arr5 = [1,2,3]

In [3]:
type(arr5)

list

In [4]:
import array
my_array = array.array('i', [1, 2, 3, 4, 5])
my_array

array('i', [1, 2, 3, 4, 5])

In [5]:
import numpy as np

In [6]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [3,4,5,6,7]

In [7]:
arr = np.array([my_lst1,my_lst2,my_lst3])

In [8]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [9]:
arr[1:,2:4]

array([[4, 5],
       [5, 6]])

In [10]:
arr[1:,1:4]

array([[3, 4, 5],
       [4, 5, 6]])

In [11]:
 arr = np.array([1,2,3,4,5])

In [12]:
arr

array([1, 2, 3, 4, 5])

In [13]:
arr[3:] = 100

In [14]:
arr

array([  1,   2,   3, 100, 100])

In [15]:
arr1 = arr
arr1[4:] = 500
arr1

array([  1,   2,   3, 100, 500])

In [16]:
arr

array([  1,   2,   3, 100, 500])

In [17]:
arr4 = arr.copy()
arr4

array([  1,   2,   3, 100, 500])

In [18]:
arr4[2:3] = 200
arr4

array([  1,   2, 200, 100, 500])

In [19]:
arr4[4]

np.int64(500)

In [20]:
#playing with dataframes
import numpy as np
import pandas as pd

In [23]:
df = pd.DataFrame(np.arange(0,20).reshape(4,5), columns = ["c1", "c2", "c3", "c4", "c5"], index = ['r1', 'r2', 'r3', 'r4'])
df

c1  c2  c3  c4  c5
r1   0   1   2   3   4
r2   5   6   7   8   9
r3  10  11  12  13  14
r4  15  16  17  18  19

In [24]:
df.iloc[:,1:]

c2  c3  c4  c5
r1   1   2   3   4
r2   6   7   8   9
r3  11  12  13  14
r4  16  17  18  19

In [27]:
#converting dataframes to array
df.iloc[:,2:].values #.reshape(3,4)

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [28]:
df.isnull().sum() #important to check null values

c1    0
c2    0
c3    0
c4    0
c5    0
dtype: int64

In [30]:
df['c1'].value_counts()

c1
0     1
5     1
10    1
15    1
Name: count, dtype: int64

In [35]:
df['c4'].unique()

array([ 3,  8, 13, 18])

In [37]:
df[['c2','c3']]

c2  c3
r1   1   2
r2   6   7
r3  11  12
r4  16  17

### Functions

In [50]:
def odd_eve(num):
    if num%2 == 0:
        return f'{num} is even number.'
    else:
        return f'{num} is odd number.'

In [51]:
odd_eve(235)

'235 is odd number.'

In [75]:
lst = [1,2,3,4,5,6,7]

In [53]:
odd_eve(lst)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [56]:
for item in lst:
    ans = odd_eve(item)
    print(ans)

1 is odd number.
2 is even number.
3 is odd number.
4 is even number.
5 is odd number.
6 is even number.
7 is odd number.


In [57]:
#positional and keyword arguments

def hello(name, age=18):
    print(f'{name} is my name and {age} is my age')

In [58]:
hello('ham')

ham is my name and 18 is my age


In [59]:
def hello(*args, **kwargs):
    print(f'{args} is my name and {kwargs} is my age')

In [61]:
hello('ham', 'suji', age=22, next=23)

('ham', 'suji') is my name and {'age': 22, 'next': 23} is my age


In [62]:
lst=['ham','suji']
dict={'age':22, 'next': 23}

In [63]:
hello(lst,dict)

(['ham', 'suji'], {'age': 22, 'next': 23}) is my name and {} is my age


In [64]:
hello(*lst,**dict)

('ham', 'suji') is my name and {'age': 22, 'next': 23} is my age


### Lambda functions

In [65]:
def addition(a,b):
    return a+b

In [67]:
addition(453,2435)

2888

In [70]:
lamb = lambda x,y : x+y
lamb(23,32)

55

In [72]:
eve_odd = lambda a : a%2==0
eve_odd(52352)

True

### Map function

In [77]:
#above in an example for loop is used instead of using for we can use map function as it is faster than a loop. If a number of values are to be passed to perform a function.
lst = [543,345,23,65,24,654,24,6,63,5,5462,36,67,4,6,8,5,6,35,6456,907]
map(odd_eve,lst)

In [81]:
list(map(odd_eve, lst))

['543 is odd number.',
 '345 is odd number.',
 '23 is odd number.',
 '65 is odd number.',
 '24 is even number.',
 '654 is even number.',
 '24 is even number.',
 '6 is even number.',
 '63 is odd number.',
 '5 is odd number.',
 '5462 is even number.',
 '36 is even number.',
 '67 is odd number.',
 '4 is even number.',
 '6 is even number.',
 '8 is even number.',
 '5 is odd number.',
 '6 is even number.',
 '35 is odd number.',
 '6456 is even number.',
 '907 is odd number.']

### Filter function

It only returns the value that satisfies a condition unlike map where the output of the values through the condition is returned

In [82]:
list(filter(lambda num: num%2==0, lst))

[24, 654, 24, 6, 5462, 36, 4, 6, 8, 6, 6456]

In [83]:
list(map(lambda num: num%2==0, lst))

[False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False]